#+TITLE: To Dos

* References:

+ [[https://github.com/p3r7/awesome-elisp][awesome-lisp.]]
+ https://www.reddit.com/r/emacs/comments/9lv1fd/a_simple_guide_to_writing_publishing_emacs/

* Inbox
** TODO [#A] Divide my org-agenda in multiple files within a 'agenda' directory.
** TODO [#A] Try out org-super-agenda, after customizing org module. https://github.com/alphapapa/org-super-agenda
** TODO [0/4] Lots to document:

- [ ] Keybindings
- [ ] Dash integration
- [ ] ex-commands

[[file:~/.config/doom/config.org::*lookup][lookup]]

** TODO https://github.com/folke/splashcii THIS BUT IN ELISP.

https://ostechnix.com/how-to-convert-images-into-ascii-format-in-linux/

This is also interesting, probably won't use it though. https://github.com/EnotionZ/jscii

** TODO [#B] [[file:config.org::*Org]] https://github.com/m-cat/org-recur#time-of-day Utilizar esto para los schedule clases de japones.

MEJORAR mis diary s-exp con ~let~. ~current-time~ y las funciones en =time-date.el=,
Si esto no me convence, entonces:

This package extends org-mode and org-agenda with support for defining recurring
tasks and easily scheduling them.

By adding some simple syntax to anywhere in the task heading you can control how
often the task should recur. Examples:

    |+2|: Recur every other day.
    |+w|: Recur every week.
    |1|: Recur on the first of every month.
    |Thu|: Recur every Thursday.
    |Sun,Sat|: Recur every Sunday and Saturday.*
    |Wkdy|: Recur every weekday.*

The syntax is the same as the one already used by org-schedule, with examples of
additional syntax, provided by org-recur, marked by *.

First, we declare the package.

#+begin_src elisp :tangle packages.el
(package! org-recur)
#+end_src

#+begin_src elisp
(use-package! org-recur
  :defer t)
#+end_src

** WAIT for HSLINER to refactor cli!

*** defcli! to auto install this configuration.

Installation of the config may require to manually uncomment 'literate' module
and run doom sync, create script for that?

** TODO [#B] Add org-super-agenda and better divide my tasks headings..
** TODO https://github.com/tecosaur/screenshot
